service: telegram-bot

package:
  individually: true

plugins:
  - serverless-offline
  - serverless-domain-manager
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'develop'}
  apiGateway:
    shouldStartNameWithService: true
  environment:
    API_KEY_EXAMPLE: ${self:custom.secrets.API_KEY_EXAMPLE.${self:provider.stage}}

functions:
  main:
    handler: src/chats/index.handler
    events:
      - http:
          method: any
          path: /chats/{any+}

custom:
  customDomain:
    domainName: ${self:custom.secrets.DOMAIN.${self:provider.stage}}
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
  webpack:
    webpackConfig: "webpack.config.js"
    packager: "yarn"
    includeModules: true
  secrets:
    stages:
      - develop
      - staging
      - production
    DOMAIN:
      develop: ${file(./secrets.yml):DOMAIN}
      staging: ${env:DOMAIN}
      production: ${env:DOMAIN}
    API_KEY_EXAMPLE:
      develop: ${file(./secrets.yml):API_KEY_EXAMPLE}
      staging: ${env:API_KEY_EXAMPLE}
      production: ${env:API_KEY_EXAMPLE}
